title: 'BitDevsKSM'
tagline: 'BitDevsKSM is a meetup devoted to the research and development of Bitcoin for developers in Kisumu, Kenya and surrounding areas.'

menu:
  - {name: 'X', url: '#', external: true}
  - {name: 'Discord', url: '#', external: true}
  - {name: 'Luma', url: '#', external: true}
